stty -ixon

test -s ~/.alias && . ~/.alias || true
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
export PATH=$PATH:/home/cyc/bin:/usr/local/sbin:/usr/sbin

export NO_AWT_MITSHM=true
export CSHEDIT=vim
if [ "$TMUX" = "" ]
then
    export TERM=xterm-256color
fi

autoload -Uz promptinit                                                                                                                                      
autoload -U colors && colors                                                                                                                                 
promptinit                                                                                                                                                   
                                                                                                                                                             
autoload -U select-word-style                                                                                                                                
select-word-style bash                                                                                                                                      

#Keep 1000 lines of history within the shell and save it to ~/.zsh_history: 
HISTSIZE=10000                                                               
SAVEHIST=10000                                                               
HISTFILE=~/.zsh_history                                                      

export VISUAL='vim' 
export EDITOR="$VISUAL"

source ~/antigen.zsh
# Load the oh-my-zsh's library.
antigen use oh-my-zsh
# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
# Load the theme.
antigen theme gnzh
# Tell antigen that you're done.
antigen apply
#RPROMPT="%{$fg[cyan]%}[%* on %D]%{$reset_color%}"                                                                                                            

alias ls='ls --color=auto'                                                   
alias la='ls -A'                                                             
alias l='ls -lah'                                                   
alias grep='grep --color -n'                                             
alias df='df -h'
alias ssh='TERM=xterm ssh'

# Use modern completion system                                                                        
autoload -Uz compinit                                                                                 

# Key maping:
# Help:
#   type bindkey in zsh shell and you'll see list of bound 
#   keys.
bindkey "^[l" forward-char
bindkey "^[j" backward-char
bindkey "^[i" up-line-or-history
bindkey "^[k" down-line-or-history
bindkey "^[L" forward-word
bindkey "^[J" backward-word
bindkey "^[f" delete-char
bindkey "^[d" backward-delete-charcompinit                                                                                              

